"""aisongtool.tools_install — provision the isolated demucs-uv / whisperx-uv envs.

Demucs and WhisperX each need their own pinned torch build (so pip/uv never
cross-upgrades one stack's torch from under the other — the same reason the
Docker image uses two separate venvs). Native (non-Docker) runs get the same
isolation via two sibling ``uv`` projects, ``demucs-uv/`` and ``whisperx-uv/``,
provisioned by this module. At runtime, ``toolrunner.venv_python()`` invokes
each env's interpreter directly rather than ``uv run``.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Callable

from .paths import data_dir
from .toolrunner import find_uv, venv_python

LogFn = Callable[[str], None]

ROOT = data_dir()

# Each env pins its own torch version (matching Dockerfile / Dockerfile.gpu
# where applicable) and uses whichever PyTorch wheel index actually ships
# that version for CUDA — newer whisperx releases require a newer torch than
# demucs does, so a single shared index/version does not work for both.
ENV_SPECS: dict[str, dict] = {
    "demucs-uv": {
        "deps": ["torch==2.5.1", "torchaudio==2.5.1", "demucs==4.0.1", "soundfile"],
        "cuda_index": "https://download.pytorch.org/whl/cu121",
    },
    "whisperx-uv": {
        # No explicit torch/torchaudio pin: let whisperx's own requirement
        # (torch~=2.8.0 as of whisperx 3.7.4) resolve from the index below.
        "deps": ["whisperx==3.7.4"],
        "cuda_index": "https://download.pytorch.org/whl/cu128",
    },
    "zimage-uv": {
        # Z-Image-Turbo, via the pre-quantized 4-bit build
        # (unsloth/Z-Image-Turbo-unsloth-bnb-4bit) rather than the original
        # Tongyi-MAI/Z-Image-Turbo bf16 weights — about a quarter of the
        # download (~3-4GB vs ~12GB) and the same fraction of VRAM, and it
        # works on any CUDA GPU (the FP8 alternative needs NVIDIA Transformer
        # Engine + a Blackwell-class GPU to actually save VRAM, which most
        # consumer cards don't have). bitsandbytes deserializes the 4-bit
        # weights. Needs diffusers from source (the ZImagePipeline isn't in a
        # PyPI release yet as of writing). torch is pinned (not left to
        # resolve freely, unlike whisperx-uv) because diffusers' git HEAD has
        # no floor that keeps it on a version with a published +cu128 wheel —
        # an unpinned resolve picked 2.12.1, which cu128's index doesn't ship.
        "deps": [
            "torch==2.8.0", "diffusers @ git+https://github.com/huggingface/diffusers.git",
            "transformers", "accelerate", "safetensors", "pillow", "gradio", "bitsandbytes",
        ],
        "cuda_index": "https://download.pytorch.org/whl/cu128",
    },
    "syrex-uv": {
        # The "Syrex" video template — an audio-reactive visualizer (curved
        # baseline, tower-shaped frequency spikes, panning background,
        # bass-driven chromatic aberration). Pure CPU signal processing/image
        # work (numpy/scipy FFT + opencv frame compositing + Pillow for
        # custom-font text) — no torch, no GPU, nothing to swap to a CUDA
        # wheel for (see ensure_env's `spec.get("cuda_index")` guard below).
        "deps": ["numpy", "scipy", "opencv-python", "pillow"],
    },
}


class SetupError(RuntimeError):
    pass


def _which(exe: str) -> str | None:
    return shutil.which(exe)


def find_nvidia_smi() -> str | None:
    where = _which("nvidia-smi")
    if where:
        return where
    if sys.platform == "win32":
        prog = os.environ.get("ProgramW6432") or os.environ.get("ProgramFiles", r"C:\Program Files")
        for candidate in (
            Path(r"C:\Windows\System32\nvidia-smi.exe"),
            Path(prog) / "NVIDIA Corporation" / "NVSMI" / "nvidia-smi.exe",
        ):
            if candidate.is_file():
                return str(candidate)
    return None


def has_gpu() -> bool:
    if find_nvidia_smi() is not None:
        return True
    if sys.platform == "win32":
        try:
            out = subprocess.run(
                ["wmic", "path", "Win32_VideoController", "get", "AdapterCompatibility"],
                capture_output=True, text=True, timeout=8,
            ).stdout
            if "NVIDIA" in out:
                return True
        except Exception:
            pass
    return False


def default_gpu_mode() -> str:
    """cu121 torch wheels exist for Windows/Linux only and only help with an NVIDIA GPU."""
    if sys.platform in ("win32", "linux") and has_gpu():
        return "cuda"
    return "cpu"


def _write_pyproject(dest: Path, name: str, deps: list[str]) -> None:
    dep_lines = ",\n    ".join(f'"{d}"' for d in deps)
    content = (
        f"# Auto-generated by `aisongtool setup`. Isolated uv env for {name}.\n"
        "[project]\n"
        f'name = "{name}"\n'
        'version = "0.0.0"\n'
        'requires-python = ">=3.10,<3.13"\n'
        "dependencies = [\n    "
        f"{dep_lines}\n]\n"
    )
    (dest / "pyproject.toml").write_text(content, encoding="utf-8")


def ensure_env(env_name: str, gpu_mode: str, log: LogFn = print) -> None:
    if env_name not in ENV_SPECS:
        raise SetupError(f"unknown env '{env_name}'. Known: {', '.join(ENV_SPECS)}")
    try:
        uv = find_uv()
    except RuntimeError as exc:
        raise SetupError(str(exc)) from exc

    spec = ENV_SPECS[env_name]
    dest = ROOT / env_name
    dest.mkdir(parents=True, exist_ok=True)

    # Always rewrite pyproject.toml from the current ENV_SPECS entry (cheap,
    # deterministic — a no-op if nothing changed) rather than only on first
    # install. Gating this on `pyproject.exists()` meant a later ENV_SPECS
    # change (e.g. adding "gradio" to zimage-uv's deps) silently never
    # reached an already-provisioned env: clicking "Install" again looked
    # like it worked but changed nothing, and the only way to actually pick
    # up the new dependency was a manual `uv add` outside the app — which
    # itself re-resolves the whole lockfile and reverts the CUDA torch pin
    # below, the exact trap this loop now avoids by reapplying it every time.
    log(f"Writing isolated uv environment definition for {env_name}...")
    _write_pyproject(dest, env_name, spec["deps"])

    log(f"$ uv sync (cwd={dest})")
    proc = subprocess.run([uv, "sync"], cwd=str(dest))
    if proc.returncode != 0:
        raise SetupError(f"uv sync failed for {env_name} (exit {proc.returncode})")

    # `uv sync` resolves torch from the default PyPI index, which on Windows
    # is CPU-only. Swap in the CUDA wheel afterwards with --no-deps so it
    # doesn't disturb the rest of the locked dependency graph. Re-running
    # `uv sync` later would otherwise revert this, but our runtime invokes the
    # venv's python.exe directly (see toolrunner.venv_python), never `uv run`,
    # so the swapped-in build sticks.
    # Envs with no torch dependency at all (e.g. syrex-uv) have no
    # "cuda_index" entry — nothing to reinstall as a CUDA wheel either way.
    if gpu_mode == "cuda" and spec.get("cuda_index"):
        py = venv_python(dest)
        # Pin to the exact version `uv sync` just resolved (from the default
        # CPU-only index) — `--no-deps` below means uv won't re-check
        # whisperx's torch~=2.8.0-style constraint, so an unpinned reinstall
        # could silently drift to a newer/incompatible torch release.
        version = subprocess.run(
            [str(py), "-c", "import torch; print(torch.__version__.split('+')[0])"],
            cwd=str(dest), capture_output=True, text=True,
        ).stdout.strip()
        if not version:
            raise SetupError(f"could not determine torch version installed in {env_name}")
        log(f"Reinstalling torch=={version}/torchaudio=={version} with CUDA wheels ({spec['cuda_index']})...")
        proc = subprocess.run(
            [uv, "pip", "install", "--python", str(py),
             f"torch=={version}", f"torchaudio=={version}",
             "--index-url", spec["cuda_index"],
             "--force-reinstall", "--no-deps"],
            cwd=str(dest),
        )
        if proc.returncode != 0:
            raise SetupError(f"CUDA torch reinstall failed for {env_name} (exit {proc.returncode})")


def setup_envs(gpu: str = "auto", log: LogFn = print) -> None:
    gpu_mode = gpu if gpu in ("cuda", "cpu") else default_gpu_mode()
    if gpu_mode == "cuda":
        detail = "NVIDIA GPU detected" if gpu == "auto" else "forced with --cuda"
        log(f"Torch build: CUDA ({detail})")
    else:
        detail = "no NVIDIA GPU detected" if gpu == "auto" else "forced with --cpu"
        log(f"Torch build: CPU ({detail}) — works on any machine, but much slower.")

    for env_name in ENV_SPECS:
        ensure_env(env_name, gpu_mode, log=log)

    log("Setup complete.")


def envs_provisioned() -> bool:
    return all((ROOT / name / "pyproject.toml").exists() for name in ENV_SPECS)


def doctor() -> dict:
    """Structured status report for the Setup tab: prerequisites + per-env state."""
    from . import ace_step
    from .toolrunner import find_ffmpeg, find_uv

    def _try(fn) -> str | None:
        try:
            return fn()
        except Exception:
            return None

    envs = {}
    for env_name in ENV_SPECS:
        env_dir = ROOT / env_name
        py = venv_python(env_dir)
        envs[env_name] = {
            "provisioned": (env_dir / "pyproject.toml").exists(),
            "venv_python": str(py) if py.exists() else None,
        }

    return {
        "uv": _try(find_uv),
        "ffmpeg": _try(find_ffmpeg),
        "nvidia_smi": find_nvidia_smi(),
        "gpu": gpu_status(),
        "envs": envs,
        "ace_step": {
            "cloned": ace_step.is_cloned(),
            "synced": ace_step.is_synced(),
            "dir": str(ace_step.dest_dir()),
        },
    }


def gpu_status() -> dict:
    cuda_available = False
    cuda_device: str | None = None
    try:
        import torch  # type: ignore

        cuda_available = bool(torch.cuda.is_available())
        if cuda_available:
            cuda_device = torch.cuda.get_device_name(0)
    except Exception:
        pass
    return {
        "nvidia_smi": has_gpu(),
        "cuda_available_in_main_env": cuda_available,
        "cuda_device": cuda_device,
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        prog="aisongtool setup",
        description="Provision the isolated demucs-uv / whisperx-uv environments with uv.",
    )
    gpu_group = ap.add_mutually_exclusive_group()
    gpu_group.add_argument("--cpu", action="store_true", help="Force CPU torch builds (default: auto-detect).")
    gpu_group.add_argument("--cuda", action="store_true", help="Force CUDA torch builds (default: auto-detect).")
    args = ap.parse_args(argv)

    gpu = "cpu" if args.cpu else "cuda" if args.cuda else "auto"
    try:
        setup_envs(gpu=gpu)
    except SetupError as exc:
        print(f"[setup] {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
