# PyInstaller spec for the standalone AiSongTool build (one-folder + macOS .app).
#
#   uv run pyinstaller packaging/aisongtool.spec
#
# Produces dist/AiSongTool/ on Windows/Linux and dist/AiSongTool.app/ on macOS.
#
# Unlike mangaEasy's spec, no torch/demucs/whisperx excludes are needed: the
# main `aisongtool` package never imports them — they live only in the
# separately-provisioned demucs-uv/whisperx-uv envs (aisongtool/tools_install.py),
# downloaded by `aisongtool setup` after install, not bundled here.

import sys as _sys
import os
import tomllib
from pathlib import Path
from PyInstaller.utils.hooks import collect_submodules

ROOT = Path(SPECPATH).resolve().parent  # repo root (spec lives in packaging/)
PKG = ROOT / "aisongtool"
VERSION = os.environ.get("AISONGTOOL_VERSION")
if not VERSION:
    with open(ROOT / "pyproject.toml", "rb") as _f:
        VERSION = tomllib.load(_f)["project"]["version"]

# Platform-appropriate icon file
if _sys.platform == "darwin":
    _icon = ROOT / "packaging" / "icon.icns"  # generated by CI before this runs
    ICON = str(_icon) if _icon.exists() else None
elif _sys.platform == "win32":
    ICON = str(ROOT / "packaging" / "icon.ico")
else:
    ICON = str(ROOT / "packaging" / "icon.png")

hiddenimports = (
    collect_submodules("aisongtool")
    + collect_submodules("webview")
    + collect_submodules("nicegui")
)

a = Analysis(
    [str(ROOT / "packaging" / "launcher.py")],
    pathex=[str(ROOT)],
    datas=[
        (str(PKG), "aisongtool"),
        (str(ROOT / "workers"), "workers"),
        (str(ROOT / "packaging" / "icon.png"), "."),
        (str(ROOT / "packaging" / "icon.ico"), "."),
    ],
    hiddenimports=hiddenimports,
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="aisongtool",
    console=False,  # GUI subsystem — no console window
    icon=ICON,
    upx=False,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name="AiSongTool",
)

# macOS: wrap in a proper .app bundle so Finder shows the icon and the app
# behaves like a native macOS application
if _sys.platform == "darwin":
    app = BUNDLE(
        coll,
        name="AiSongTool.app",
        icon=ICON,
        bundle_identifier="com.aisongtool.app",
        info_plist={
            "CFBundleName": "AiSongTool",
            "CFBundleDisplayName": "AiSongTool",
            "CFBundleShortVersionString": VERSION,
            "NSHighResolutionCapable": True,
            "NSRequiresAquaSystemAppearance": False,  # supports dark mode
        },
    )
